name: Rust

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/moss

      - name: Package
        run: zip -r -9 moss_linux.zip target/release/moss

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: moss_linux
          path: moss_linux.zip
          if-no-files-found: error 

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Package
        run: Compress-Archive -LiteralPath 'target/release/moss.exe' -DestinationPath 'moss_win.zip'

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: moss_win
          path: moss_win.zip
          if-no-files-found: error 

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: cargo build --all --release && strip target/release/moss

      - name: Package
        run: zip -r -9 moss_darwin.zip target/release/moss

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: moss_darwin
          path: moss_darwin.zip
          if-no-files-found: error 

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download linux package
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      # - name: Release
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: latest
      #     draft: true
      #     files: |
      #       moss_linux/moss_linux.zip
      #       moss_win/moss_win.zip
      #       moss_darwin/moss_darwin.zip
